### ISSUE TITLE
Compiling latest Messages APK

### ISSUE THREAD

**Issue by mikkushukla** [slvn/android-aosp-mms#9]
Hi Slvn,
Could you please help us compiling latest Messages app from android source.
https://android.googlesource.com/platform/packages/apps/Messaging/+/3dd036dc9973f3cf10768d66e892d152a58c6dee.

Kindly let us know the steps to proceed with.

Thanks

**Comment by slvn** [comment]
Hello @mikkushukla !
Thanks for reaching me but this question is out of the scope of this repository and i don't really know what you want to do. Nevertheless, let me try to help you.

To build the official message application from Android open source follow the documentation https://source.android.com/setup/
- setup your environment
- download the branch you want to build
- build the app ```make -j8 messaging``` 

Know the app will probably linked with the system you build and won't run anywhere so you may need to do some modifications, check the commits from this project if you encouter some of this issues.

Hope this will help you. Have fun.
